export const WORDS = [
  {
    group: 1,
    translate: "начинать",
    infinitive: "begin",
    infTrans: "[bɪ`gɪn]",
    pastSimple: "began",
    simTrans: "[bɪ`gæn]",
    pastParticiple: "begun",
    partTrans: "[bɪ`gʌn]",
  },
  {
    group: 1,
    translate: "пить",
    infinitive: "drink",
    infTrans: "[drɪnk]",
    pastSimple: "drank",
    simTrans: "[drænk]",
    pastParticiple: "drunk",
    partTrans: "[drʌnk]",
  },
  {
    group: 1,
    translate: "петь",
    infinitive: "sing",
    infTrans: "[sɪŋ]",
    pastSimple: "sang",
    simTrans: "[sæŋk]",
    pastParticiple: "sung",
    partTrans: "[sʌŋk]",
  },
  {
    group: 1,
    translate: "звонить",
    infinitive: "ring",
    infTrans: "[rɪŋ]",
    pastSimple: "rang",
    simTrans: "[ræŋ]",
    pastParticiple: "rung",
    partTrans: "[rʌŋ]",
  },
  {
    group: 1,
    translate: "плыть",
    infinitive: "swim",
    infTrans: "[swɪm]",
    pastSimple: "swam",
    simTrans: "swæm",
    pastParticiple: "swum",
    partTrans: "[swʌm]",
  },
  {
    group: 2,
    translate: "сиять",
    infinitive: "shine",
    infTrans: "[ʃaɪn]",
    pastSimple: "shone",
    simTrans: "[ʃoʊn]",
    pastParticiple: "shone",
    partTrans: "[ʃoʊn]",
  },
  {
    group: 2,
    translate: "скручивать",
    infinitive: "wring",
    infTrans: "[rɪŋ]",
    pastSimple: "wrung",
    simTrans: "[rʌŋ]",
    pastParticiple: "wrung",
    partTrans: "[rʌŋ]",
  },
  {
    group: 2,
    translate: "липнуть",
    infinitive: "stick",
    infTrans: "[stɪk]",
    pastSimple: "stuck",
    simTrans: "[stʌk]",
    pastParticiple: "stuck",
    partTrans: "[stʌk]",
  },
  {
    group: 2,
    translate: "встретить",
    infinitive: "meet",
    infTrans: "[mi:t]",
    pastSimple: "met",
    simTrans: "[met]",
    pastParticiple: "met",
    partTrans: "[met]",
  },
  {
    group: 2,
    translate: "вешать",
    infinitive: "hang",
    infTrans: "[hæŋ]",
    pastSimple: "hung",
    simTrans: "[hʌŋ]",
    pastParticiple: "hung",
    partTrans: "[hʌŋ]",
  },
  {
    group: 3,
    translate: "покупать",
    infinitive: "buy",
    infTrans: "[baɪ]",
    pastSimple: "bought",
    simTrans: "[bɔ:t]",
    pastParticiple: "bought",
    partTrans: "[bɔ:t]",
  },
  {
    group: 3,
    translate: "ловить",
    infinitive: "catch",
    infTrans: "[kætʃ]",
    pastSimple: "caught",
    simTrans: "[kɔ:t]",
    pastParticiple: "caught",
    partTrans: "[kɔ:t]",
  },
  {
    group: 3,
    translate: "искать",
    infinitive: "seek",
    infTrans: "[si:k]",
    pastSimple: "sought",
    simTrans: "[sɔ:t]",
    pastParticiple: "sought",
    partTrans: "[sɔ:t]",
  },
  {
    group: 3,
    translate: "обучать",
    infinitive: "teach",
    infTrans: "[ti:tʃ]",
    pastSimple: "taught",
    simTrans: "[tɔ:t]",
    pastParticiple: "taught",
    partTrans: "[tɔ:t]",
  },
  {
    group: 3,
    translate: "думать",
    infinitive: "think",
    infTrans: "[θɪŋk]",
    pastSimple: "thought",
    simTrans: "[θɔ:t]",
    pastParticiple: "thought",
    partTrans: "[θɔ:t]",
  },
  {
    group: 4,
    translate: "строить",
    infinitive: "build",
    infTrans: "[bɪld]",
    pastSimple: "built",
    simTrans: "[bɪlt]",
    pastParticiple: "built",
    partTrans: "[bɪlt]",
  },
  {
    group: 4,
    translate: "отправлять",
    infinitive: "send",
    infTrans: "[send]",
    pastSimple: "sent",
    simTrans: "[sent]",
    pastParticiple: "sent",
    partTrans: "[sent]",
  },
  {
    group: 4,
    translate: "украшать",
    infinitive: "gild",
    infTrans: "[gɪld]",
    pastSimple: "gilt",
    simTrans: "[gɪlt]",
    pastParticiple: "gilt",
    partTrans: "[gɪlt]",
  },
  {
    group: 4,
    translate: "отдалживать",
    infinitive: "lend",
    infTrans: "[lend]",
    pastSimple: "lent",
    simTrans: "[lent]",
    pastParticiple: "lent",
    partTrans: "[lent]",
  },
  {
    group: 4,
    translate: "гнуть",
    infinitive: "bend",
    infTrans: "[bend]",
    pastSimple: "bent",
    simTrans: "[bent]",
    pastParticiple: "bent",
    partTrans: "[bent]",
  },
  {
    group: 5,
    translate: "дуть",
    infinitive: "blow",
    infTrans: "[bloʊ]",
    pastSimple: "blew",
    simTrans: "[blu:]",
    pastParticiple: "blown",
    partTrans: "[bləun]",
  },
  {
    group: 5,
    translate: "летать",
    infinitive: "fly",
    infTrans: "[flaɪ]",
    pastSimple: "flew",
    simTrans: "[flu:]",
    pastParticiple: "flown",
    partTrans: "[floʊn]",
  },
  {
    group: 5,
    translate: "знать",
    infinitive: "know",
    infTrans: "[noʊ]",
    pastSimple: "knew",
    simTrans: "[nju:]",
    pastParticiple: "known",
    partTrans: "[noʊn]",
  },
  {
    group: 5,
    translate: "бросать",
    infinitive: "throw",
    infTrans: "[θroʊ]",
    pastSimple: "threw",
    simTrans: "[θru:]",
    pastParticiple: "thrown",
    partTrans: "[θroʊn]",
  },
  {
    group: 5,
    translate: "выращивать",
    infinitive: "grow",
    infTrans: "[groʊ]",
    pastSimple: "grew",
    simTrans: "[gru:]",
    pastParticiple: "grown",
    partTrans: "[groʊn]",
  },
  {
    group: 6,
    translate: "класть",
    infinitive: "put",
    infTrans: "[pʊt]",
    pastSimple: "put",
    simTrans: "[pʊt]",
    pastParticiple: "put",
    partTrans: "[pʊt]",
  },
  {
    group: 6,
    translate: "вязать",
    infinitive: "knit",
    infTrans: "[nɪt]",
    pastSimple: "knit",
    simTrans: "[nɪt]",
    pastParticiple: "knit",
    partTrans: "[nɪt]",
  },
  {
    group: 6,
    translate: "стоить",
    infinitive: "cost",
    infTrans: "[kɒst]",
    pastSimple: "cost",
    simTrans: "[kɒst]",
    pastParticiple: "cost",
    partTrans: "[kɒst]",
  },
  {
    group: 6,
    translate: "класть",
    infinitive: "set",
    infTrans: "[set]",
    pastSimple: "set",
    simTrans: "[set]",
    pastParticiple: "set",
    partTrans: "[set]",
  },
  {
    group: 6,
    translate: "восстанавливать",
    infinitive: "reset",
    infTrans: "[reset]",
    pastSimple: "reset",
    simTrans: "[reset]",
    pastParticiple: "reset",
    partTrans: "[reset]",
  },
  {
    group: 7,
    translate: "возникать",
    infinitive: "arise",
    infTrans: "[ə`raɪz]",
    pastSimple: "arose",
    simTrans: "[ə'rəʊz]",
    pastParticiple: "arisen",
    partTrans: "[ə'rɪz(ə)n]",
  },
  {
    group: 7,
    translate: "писать",
    infinitive: "write",
    infTrans: "[raɪt]",
    pastSimple: "wrote",
    simTrans: "[roʊt]",
    pastParticiple: "written",
    partTrans: "[rɪtn]",
  },
  {
    group: 7,
    translate: "идти",
    infinitive: "go",
    infTrans: "[идти]",
    pastSimple: "went",
    simTrans: "[went]",
    pastParticiple: "gone",
    partTrans: "[gɒn]",
  },
  {
    group: 7,
    translate: "видеть",
    infinitive: "see",
    infTrans: "[si:]",
    pastSimple: "saw",
    simTrans: "[sɔ:]",
    pastParticiple: "seen",
    partTrans: "[si:n]",
  },
  {
    group: 7,
    translate: "просыпаться",
    infinitive: "awake",
    infTrans: "[əˈweɪk]",
    pastSimple: "awoke",
    simTrans: "[ə'wəʊk]",
    pastParticiple: "awoken",
    partTrans: "[ə'wəuk(ə)n]",
  },
];
